version: '3.8'

volumes:
  pgdata:

services:
  postgres:
    container_name: postgres
    image: postgres:14.7
    restart: on-failure
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: tasks
    volumes:
      - pgdata:/var/lib/postgresql/data
